Start
webui-nodejs-027/sound-party pull request #1
Opened 2019-05-20 13:37 UTC by khavelius

2019-05-21 10:42 UTC, maksym-khavelov reviewed
Move entities to schema
Move models to entities
Services works with repositories and entities

2019-05-21 10:42 UTC, khavelius commented on src/db/models/AuthorModel.js
> +    this.name = name;
Add abstract class

2019-05-21 10:48 UTC, maksym-khavelov reviewed
Rename Client to Base

2019-05-21 10:48 UTC, khavelius commented on src/routes/mainRoute.js
> +const express = require('express');
change to static middleware

2019-05-22 11:18 UTC, vadym-dolzhenko requested changes

2019-05-22 11:18 UTC, vadym-dolzhenko commented on src/entities/AuthorModel.js
> +  constructor(name) {
You need to create a base class with the name property

2019-05-22 13:12 UTC, vadym-dolzhenko approved these changes

2019-05-22 13:18 UTC, merged